# -*- coding: utf-8 -*-
"""missile-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/124YnpwUXyWuxKl4ipd0UtF8BXJ2D8z5j

## Создать папки, задать пути:
"""

from os.path import exists, dirname, join
from os import mkdir

datadir = '/tmp/missile-dataset'
sample_file_path = join(datadir, 'military_bases.txt')
outfile = join(datadir, 'out.txt')
radius = 10
nbases = 1_000
gitrepo = 'https://gitlab.sirius-web.org/python-students-22/attack-isaeva.git'
gitdir = '/tmp/missile'
scriptpath = join(gitdir, 'main.py')

! mkdir -p $datadir
! rm -rf $gitdir

"""## Сгенерировать исходные данные"""

import numpy as np

np.random.seed(0)
data = np.random.rand(nbases, 3)
data = (data * 100).astype(np.int32)
data[:,2] += 1
np.savetxt(sample_file_path, data, fmt='%d')

"""## Запустить программу, измерить время"""

# Commented out IPython magic to ensure Python compatibility.
! git clone $gitrepo $gitdir
# %time ! python $scriptpath $sample_file_path $radius > $outfile

! cat $outfile

"""## Проверить результат"""

import numpy as np

x,y,value = np.loadtxt(outfile)

data = np.loadtxt(sample_file_path, dtype=np.int32)
mask = (data[:,0] - x) ** 2 + (data[:,1] - y) ** 2 <= radius**2
actual_value = sum(data[mask,2])
assert actual_value == value